#= require jquery
#= require jquery_ujs
#= require handlebars
#= require ember
#= require ember-data
#= require_self
#= require emblem-test
#= require_tree .
window.EmblemTest = Em.Application.create()
